# Этот файл содержит настройки для плагина AnarchyRegions.
# Все настройки можно изменить в этом файле.
# После изменения настроек необходимо перезапустить сервер.

settings:
  region-cache-size: 1500 # Максимальное количество регионов в кэше. Влияет на потребление памяти и производительность.
  hologram-update-interval-ticks: 20 # Интервал обновления holograms в тиках.  1 тик = 50мс. По умолчанию 20 тиков = 1 секунда.
  region-update-interval-ticks: 100 # Интервал обновления регионов в тиках (5 секунд по умолчанию)
  region-update-batch-size: 10 # Размер батча для обновления регионов за один цикл
  region-max-updates-per-tick: 5 # Максимальное количество обновлений регионов за один тик (для предотвращения лагов)
  request-max-per-player: 5 # Максимальное количество активных приглашений, отправленных одним игроком
  request-max-total: 250 # Общий лимит приглашений в памяти (LRU, старые удаляются первыми)